In [1]:
import bs4
import pandas as pd
import requests

In [2]:
nm=[]
pr=[]
rt=[]




#n=int(input("Enter no. of pages which you want to scrape =   "))
for i in range(1,51):
    url="https://books.toscrape.com/catalogue/page-"+str(i)+".html"
    res=requests.get(url)
    data=bs4.BeautifulSoup(res.text,"html.parser")
    #print(data.prettify())
    
    
    BookPrice=data.find("p",{"class":"price_color"})
    #print(BookPrice)
    BookRating=data.find("article",{"class":"product_pod"})
    BookRating.find('p').get('class')[1]
    BookName=data.find("h3")
    BookName.a.get("title")
    
    
    for j in data.find_all("h3"):
        nm.append(j.a.get("title"))
        
        
    for j in data.find_all("p",{"class":"price_color"}):
        pr.append(j.text.strip()[1:])
        
        
        
    for j in data.find_all("article",{"class":"product_pod"}):
        rt.append(j.find('p').get('class')[1])
        
    data1=pd.DataFrame({"Books Name":nm,"Books Price":pr,"Books Rating":rt})
    #data1
    
    data1.to_excel("Data.xlsx",index=False)
    df=pd.read_excel("Data.xlsx")
    print(df.shape)
    print(df)
    
    i+=1

(20, 3)
                                           Books Name Books Price Books Rating
0                                A Light in the Attic      £51.77        Three
1                                  Tipping the Velvet      £53.74          One
2                                          Soumission      £50.10          One
3                                       Sharp Objects      £47.82         Four
4               Sapiens: A Brief History of Humankind      £54.23         Five
5                                     The Requiem Red      £22.65          One
6   The Dirty Little Secrets of Getting Your Dream...      £33.34         Four
7   The Coming Woman: A Novel Based on the Life of...      £17.93        Three
8   The Boys in the Boat: Nine Americans and Their...      £22.60         Four
9                                     The Black Maria      £52.15          One
10     Starving Hearts (Triangular Trade Trilogy, #1)      £13.99          Two
11                              Shakespeare's Sonnets      £20.66         Four
12                                        Set Me Free      £17.46         Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...      £52.29         Five
14                          Rip it Up and Start Again      £35.02         Five
15  Our Band Could Be Your Life: Scenes from the A...      £57.25        Three
16                                               Olio      £23.88          One
17  Mesaerion: The Best Science Fiction Stories 18...      £37.59          One
18                       Libertarianism for Beginners      £51.33          Two
19                            It's Only the Himalayas      £45.17          Two
(40, 3)
                                           Books Name Books Price Books Rating
0                                A Light in the Attic      £51.77        Three
1                                  Tipping the Velvet      £53.74          One
2                                          Soumission      £50.10          One
3                                       Sharp Objects      £47.82         Four
4               Sapiens: A Brief History of Humankind      £54.23         Five
5                                     The Requiem Red      £22.65          One
6   The Dirty Little Secrets of Getting Your Dream...      £33.34         Four
7   The Coming Woman: A Novel Based on the Life of...      £17.93        Three
8   The Boys in the Boat: Nine Americans and Their...      £22.60         Four
9                                     The Black Maria      £52.15          One
10     Starving Hearts (Triangular Trade Trilogy, #1)      £13.99          Two
11                              Shakespeare's Sonnets      £20.66         Four
12                                        Set Me Free      £17.46         Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...      £52.29         Five
14                          Rip it Up and Start Again      £35.02         Five
15  Our Band Could Be Your Life: Scenes from the A...      £57.25        Three
16                                               Olio      £23.88          One
17  Mesaerion: The Best Science Fiction Stories 18...      £37.59          One
18                       Libertarianism for Beginners      £51.33          Two
19                            It's Only the Himalayas      £45.17          Two
20                                        In Her Wake      £12.84          One
21                                    How Music Works      £37.32          Two
22  Foolproof Preserving: A Guide to Small Batch J...      £30.52        Three
23                         Chase Me (Paris Nights #2)      £25.27         Five
24                                         Black Dust      £34.53         Five
25                      Birdsong: A Story in Pictures      £54.64        Three
26  America's Cradle of Quarterbacks: Western Penn...      £22.50        Three
27                     Aladdin and His Wonderful Lamp      £53.13        Three
28  Worlds Elsewhere: Journeys Around Shakespeareâ...      £40.30         Five
29                                     Wall and Piece      £44.18         Four
30  The Four Agreements: A Practical Guide to Pers...      £17.66         Five
31  The Five Love Languages: How to Express Heartf...      £31.05        Three
32                                  The Elephant Tree      £23.82         Five
33                             The Bear and the Piano      £36.89          One
34                                     Sophie's World      £15.94         Five
35                                        Penny Maybe      £33.29        Three
36     Maude (1883-1993):She Grew Up with the country      £18.02          Two
37                               In a Dark, Dark Wood      £19.63          One
38                                Behind Closed Doors      £52.22         Four
39                     You can't bury them all: Poems      £33.63          Two
(60, 3)
                                           Books Name Books Price Books Rating
0                                A Light in the Attic      £51.77        Three
1                                  Tipping the Velvet      £53.74          One
2                                          Soumission      £50.10          One
3                                       Sharp Objects      £47.82         Four
4               Sapiens: A Brief History of Humankind      £54.23         Five
5                                     The Requiem Red      £22.65          One
6   The Dirty Little Secrets of Getting Your Dream...      £33.34         Four
7   The Coming Woman: A Novel Based on the Life of...      £17.93        Three
8   The Boys in the Boat: Nine Americans and Their...      £22.60         Four
9                                     The Black Maria      £52.15          One
10     Starving Hearts (Triangular Trade Trilogy, #1)      £13.99          Two
11                              Shakespeare's Sonnets      £20.66         Four
12                                        Set Me Free      £17.46         Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...      £52.29         Five
14                          Rip it Up and Start Again      £35.02         Five
15  Our Band Could Be Your Life: Scenes from the A...      £57.25        Three
16                                               Olio      £23.88          One
17  Mesaerion: The Best Science Fiction Stories 18...      £37.59          One
18                       Libertarianism for Beginners      £51.33          Two
19                            It's Only the Himalayas      £45.17          Two
20                                        In Her Wake      £12.84          One
21                                    How Music Works      £37.32          Two
22  Foolproof Preserving: A Guide to Small Batch J...      £30.52        Three
23                         Chase Me (Paris Nights #2)      £25.27         Five
24                                         Black Dust      £34.53         Five
25                      Birdsong: A Story in Pictures      £54.64        Three
26  America's Cradle of Quarterbacks: Western Penn...      £22.50        Three
27                     Aladdin and His Wonderful Lamp      £53.13        Three
28  Worlds Elsewhere: Journeys Around Shakespeareâ...      £40.30         Five
29                                     Wall and Piece      £44.18         Four
30  The Four Agreements: A Practical Guide to Pers...      £17.66         Five
31  The Five Love Languages: How to Express Heartf...      £31.05        Three
32                                  The Elephant Tree      £23.82         Five
33                             The Bear and the Piano      £36.89          One
34                                     Sophie's World      £15.94         Five
35                                        Penny Maybe      £33.29        Three
36     Maude (1883-1993):She Grew Up with the country      £18.02          Two
37                               In a Dark, Dark Wood      £19.63          One
38                                Behind Closed Doors      £52.22         Four
39                     You can't bury them all: Poems      £33.63          Two
40                     Slow States of Collapse: Poems      £57.31        Three
41                              Reasons to Stay Alive      £26.41          Two
42                        Private Paris (Private #10)      £47.61         Five
43  #HigherSelfie: Wake Up Your Life. Free Your So...      £23.11         Five
44                    Without Borders (Wanderlove #1)      £45.07          Two
45                                   When We Collided      £31.77          One
46                       We Love You, Charlie Freeman      £50.27         Five
47            Untitled Collection: Sabbath Poems 2014      £14.27         Four
48  Unseen City: The Majesty of Pigeons, the Discr...      £44.18         Four
49                                     Unicorn Tracks      £18.78        Three
50  Unbound: How Eight Technologies Made Us Human,...      £25.52          One
51  Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRo...      £16.28          One
52  Throwing Rocks at the Google Bus: How Growth B...      £31.12        Three
53                                    This One Summer      £19.49         Four
54                                             Thirst      £17.27         Five
55        The Torch Is Passed: A Harding Family Story      £19.09          One
56                    The Secret of Dreadwillow Carse      £56.13          One
57  The Pioneer Woman Cooks: Dinnertime: Comfort C...      £56.41          One
58                                The Past Never Ends      £56.50         Four
59  The Natural History of Us (The Fine Art of Pre...      £45.22        Three

(80, 3)
                                           Books Name Books Price Books Rating
0                                A Light in the Attic      £51.77        Three
1                                  Tipping the Velvet      £53.74          One
2                                          Soumission      £50.10          One
3                                       Sharp Objects      £47.82         Four
4               Sapiens: A Brief History of Humankind      £54.23         Five
..                                                ...         ...          ...
75                                           Security      £39.25          Two
76      Saga, Volume 6 (Saga (Collected Editions) #6)      £25.02        Three
77      Saga, Volume 5 (Saga (Collected Editions) #5)      £51.04          Two
78  Reskilling America: Learning to Labor in the T...      £19.83          Two
79  Rat Queens, Vol. 3: Demons (Rat Queens (Collec...      £50.40        Three

[80 rows x 3 columns]
(100, 3)
                                           Books Name Books Price Books Rating
0                                A Light in the Attic      £51.77        Three
1                                  Tipping the Velvet      £53.74          One
2                                          Soumission      £50.10          One
3                                       Sharp Objects      £47.82         Four
4               Sapiens: A Brief History of Humankind      £54.23         Five
..                                                ...         ...          ...
95  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...      £19.92          Two
96  Layered: Baking, Building, and Styling Spectac...      £40.11          One
97  Judo: Seven Steps to Black Belt (an Introducto...      £53.90          Two
98                                               Join      £35.67         Five
99          In the Country We Love: My Family Divided      £22.00         Four

[100 rows x 3 columns]
(120, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
115  Call the Nurse: True Stories of a Country Nurs...      £29.14
116                                            Burning      £28.81
117                                         Bossypants      £49.46
118  Bitch Planet, Vol. 1: Extraordinary Machine (B...      £37.92
119  Avatar: The Last Airbender: Smoke and Shadow, ...      £28.09

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
115         Five
116        Three
117          Two
118          Two
119          Two

[120 rows x 3 columns]
(140, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
135  The White Cat and the Monk: A Retelling of the...      £58.08
136                                  The Wedding Dress      £24.12
137                                    The Vacationers      £42.15
138  The Third Wave: An Entrepreneurâs Vision of ...      £12.61
139                                       The Stranger      £17.44

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
135         Four
136          One
137         Four
138         Five
139         Four

[140 rows x 3 columns]
(160, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
155     The Glittering Court (The Glittering Court #1)      £44.28
156                              The Girl on the Train      £55.02
157                                The Genius of Birds      £17.24
158                                The Emerald Mystery      £23.15
159  The Cookies & Cups Cookbook: 125+ sweet & savo...      £41.25

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
155          One
156          Two
157          One
158          Two
159          One

[160 rows x 3 columns]
(180, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
175  Poses for Artists Volume 1 - Dynamic and Sitti...      £41.06
176                    Poems That Make Grown Women Cry      £14.19
177                                  Nightingale, Sing      £38.28
178                         Night Sky with Exit Wounds      £41.05
179                                       Mrs. Houdini      £30.25

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
175          One
176         Four
177          One
178          One
179         Five

[180 rows x 3 columns]
(200, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
195                                  Eureka Trivia 6.0      £54.59
196  Drive: The Surprising Truth About What Motivat...      £34.95
197            Done Rubbed Out (Reightman & Bailey #1)      £37.72
198                  Doing It Over (Most Likely To #1)      £35.61
199  Deliciously Ella Every Day: Quick and Easy Rec...      £42.16

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
195         Four
196         Four
197         Five
198        Three
199        Three

[200 rows x 3 columns]
(220, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
215    Zealot: The Life and Times of Jesus of Nazareth      £24.70
216                                       You (You #1)      £43.61
217  Wonder Woman: Earth One, Volume One (Wonder Wo...      £37.34
218                                         Wild Swans      £14.36
219  Why the Right Went Wrong: Conservatism--From G...      £52.65

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
215        Three
216         Five
217         Four
218          Two
219         Four

[220 rows x 3 columns]

(240, 3)
                                Books Name Books Price Books Rating
0                     A Light in the Attic      £51.77        Three
1                       Tipping the Velvet      £53.74          One
2                               Soumission      £50.10          One
3                            Sharp Objects      £47.82         Four
4    Sapiens: A Brief History of Humankind      £54.23         Five
..                                     ...         ...          ...
235                  The Testament of Mary      £52.67         Four
236                 The Star-Touched Queen      £46.02         Five
237                  The Songs of the Gods      £44.48         Five
238                   The Song of Achilles      £37.40         Five
239     The Rosie Project (Don Tillman #1)      £54.04          One

[240 rows x 3 columns]
(260, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
255  The Bad-Ass Librarians of Timbuktu: And Their ...      £15.77
256                The 14th Colony (Cotton Malone #11)      £39.24
257             That Darkness (Gardiner and Renner #1)      £13.92
258               Tastes Like Fear (DI Marnie Rome #3)      £10.69
259                                   Take Me with You      £45.21

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
255          One
256          One
257          One
258          One
259        Three

[260 rows x 3 columns]
(280, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
275  Overload: How to Unplug, Unwind, and Unleash Y...      £52.15
276                                    Once Was a Time      £18.28
277              Old School (Diary of a Wimpy Kid #10)      £11.83
278  No Dream Is Too High: Life Lessons From a Man ...      £21.95
279  Naruto (3-in-1 Edition), Vol. 14: Includes Vol...      £38.39

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
275        Three
276          Two
277         Five
278          Two
279          Two

[280 rows x 3 columns]
(300, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
295                   Island of Dragons (Unwanteds #7)      £29.65
296  I Know What I'm Doing -- and Other Lies I Tell...      £25.98
297                          I Am Pilgrim (Pilgrim #1)      £10.60
298  Hyperbole and a Half: Unfortunate Situations, ...      £14.75
299                         Hush, Hush (Hush, Hush #1)      £47.02

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
295          One
296         Four
297         Four
298         Five
299        Three

[300 rows x 3 columns]
(320, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
315  Demigods & Magicians: Percy and Annabeth Meet ...      £37.51
316                                 Dear Mr. Knightley      £11.21
317                               Daily Fantasy Sports      £36.58
318        Crazy Love: Overwhelmed by a Relentless God      £47.72
319        Cometh the Hour (The Clifton Chronicles #6)      £25.01

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
315         Five
316         Five
317          One
318          Two
319        Three

[320 rows x 3 columns]
(340, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
335                                    Balloon Animals      £17.03
336                                     Art Ops Vol. 1      £48.80
337  Aristotle and Dante Discover the Secrets of th...      £58.14
338                 Angels Walking (Angels Walking #1)      £34.20
339                Angels & Demons (Robert Langdon #1)      £51.48

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
335        Three
336        Three
337         Four
338          Two
339        Three

[340 rows x 3 columns]
(360, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
355  13 Hours: The Inside Account of What Really Ha...      £27.06
356                        Will You Won't You Want Me?      £13.86
357  Tipping Point for Planet Earth: How Close Are ...      £37.55
358                             The Star-Touched Queen      £32.30
359            The Silent Sister (Riley MacPherson #1)      £46.29

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
355          One
356        Three
357          One
358         Five
359         Five

[360 rows x 3 columns]
(380, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
375                    No Love Allowed (Dodge Cove #1)      £54.65
376  Murder at the 42nd Street Library (Raymond Amb...      £54.36
377                                        Most Wanted      £35.28
378                               Love, Lies and Spies      £20.55
379  How to Speak Golf: An Illustrated Guide to Lin...      £58.32

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
375         Four
376         Four
377        Three
378          Two
379         Five

[380 rows x 3 columns]

(400, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
395        Take Me Home Tonight (Rock Star Romance #3)      £53.98
396                  Sleeping Giants (Themis Files #1)      £48.74
397  Setting the World on Fire: The Brief, Astonish...      £21.15
398                                  Playing with Fire      £13.71
399              Off the Hook (Fishing for Trouble #1)      £47.67

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
395        Three
396          One
397          Two
398        Three
399        Three

[400 rows x 3 columns]
(420, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
415  A Mother's Reckoning: Living in the Aftermath ...      £19.53
416   A Gentleman's Position (Society of Gentlemen #3)      £14.75
417                                           11/22/63      £48.48
418  10% Happier: How I Tamed the Voice in My Head,...      £24.57
419  10-Day Green Smoothie Cleanse: Lose Up to 15 P...      £49.71

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
415        Three
416         Five
417        Three
418          Two
419         Five

[420 rows x 3 columns]
(440, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
435                                  Modern Day Fables      £47.44
436  If I Gave You God's Phone Number....: Searchin...      £20.91
437           Fruits Basket, Vol. 9 (Fruits Basket #9)      £33.95
438            Dress Your Family in Corduroy and Denim      £43.68
439                                Don't Forget Steven      £33.23

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
435          Two
436          One
437         Four
438        Three
439          One

[440 rows x 3 columns]
(460, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
455  The E-Myth Revisited: Why Most Small Businesse...      £36.91
456                                  South of Sunshine      £28.93
457  Smarter Faster Better: The Secrets of Being Pr...      £38.89
458               Silence in the Dark (Logan Point #4)      £58.33
459               Shadows of the Past (Logan Point #1)      £39.67

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
455          One
456          One
457         Five
458        Three
459         Five

[460 rows x 3 columns]
(480, 3)
                                Books Name Books Price Books Rating
0                     A Light in the Attic      £51.77        Three
1                       Tipping the Velvet      £53.74          One
2                               Soumission      £50.10          One
3                            Sharp Objects      £47.82         Four
4    Sapiens: A Brief History of Humankind      £54.23         Five
..                                     ...         ...          ...
475                  I'll Give You the Sun      £56.48          One
476                        I Will Find You      £44.21          One
477                      Hystopia: A Novel      £21.96         Four
478                   Howl and Other Poems      £40.45          Two
479                      History of Beauty      £10.29         Four

[480 rows x 3 columns]
(500, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
495  Unreasonable Hope: Finding Faith in the God Wh...      £46.33
496                               Under the Tuscan Sun      £37.33
497         Toddlers Are A**holes: It's Not Your Fault      £25.55
498  The Year of Living Biblically: One Man's Humbl...      £34.72
499                                          The Whale      £35.96

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
495          Two
496        Three
497          One
498          One
499         Four

[500 rows x 3 columns]
(520, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
515                                        Sister Dear      £40.20
516  Shrunken Treasures: Literary Classics, Short, ...      £52.87
517                                 Rich Dad, Poor Dad      £51.74
518                                 Raymie Nightingale      £34.41
519                             Playing from the Heart      £32.38

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
515         Four
516        Three
517          One
518          Two
519          One

[520 rows x 3 columns]
(540, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
535   Every Heart a Doorway (Every Heart A Doorway #1)      £12.16
536   Delivering the Truth (Quaker Midwife Mystery #1)      £20.89
537         Counted With the Stars (Out from Egypt #1)      £17.97
538                                 Chronicles, Vol. 1      £52.60
539  Blue Like Jazz: Nonreligious Thoughts on Chris...      £25.77

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
535         Five
536         Four
537         Five
538          Two
539          One

[540 rows x 3 columns]

(560, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
555         The Golden Compass (His Dark Materials #1)      £18.77
556                                   The God Delusion      £46.85
557  The Girl You Left Behind (The Girl You Left Be...      £15.79
558  The Fellowship of the Ring (The Lord of the Ri...      £10.27
559  The Collected Poems of W.B. Yeats (The Collect...      £15.42

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
555          One
556        Three
557          One
558          Two
559         Five

[560 rows x 3 columns]
(580, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
575  Death Note, Vol. 6: Give-and-Take (Death Note #6)      £36.39
576           Catherine the Great: Portrait of a Woman      £58.55
577             Better Homes and Gardens New Cook Book      £39.61
578     An Unquiet Mind: A Memoir of Moods and Madness      £21.30
579                   A Year in Provence (Provence #1)      £56.88

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
575        Three
576         Four
577        Three
578        Three
579         Four

[580 rows x 3 columns]
(600, 3)
                                       Books Name Books Price Books Rating
0                            A Light in the Attic      £51.77        Three
1                              Tipping the Velvet      £53.74          One
2                                      Soumission      £50.10          One
3                                   Sharp Objects      £47.82         Four
4           Sapiens: A Brief History of Humankind      £54.23         Five
..                                            ...         ...          ...
595                              The Grand Design      £13.76        Three
596                                      The Firm      £45.56        Three
597                        The Fault in Our Stars      £47.22          One
598  The False Prince (The Ascendance Trilogy #1)      £56.00         Five
599                               The Expatriates      £44.58          Two

[600 rows x 3 columns]
(620, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
615  Lola and the Boy Next Door (Anna and the Frenc...      £23.63
616                Logan Kade (Fallen Crest High #5.5)      £13.12
617                  Last One Home (New Beginnings #1)      £59.98
618                    Killing Floor (Jack Reacher #1)      £31.49
619                                  Kill the Boy Band      £15.52

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
615         Four
616          Two
617        Three
618         Four
619         Five

[620 rows x 3 columns]
(640, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
635                                             Booked      £17.49
636          Blue Lily, Lily Blue (The Raven Cycle #3)      £34.13
637     Approval Junkie: Adventures in Caring Too Much      £58.81
638                         An Abundance of Katherines      £10.00
639  America's War for the Greater Middle East: A M...      £51.22

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
635         Five
636         Five
637         Five
638         Five
639          Two

[640 rows x 3 columns]
(660, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
655                        The Demonists (Demonist #1)      £52.11
656  The Demon Prince of Momochi House, Vol. 4 (The...      £27.88
657  The Bone Hunters (Lexy Vaughan & Steven Macaul...      £59.71
658           The Beast (Black Dagger Brotherhood #14)      £46.08
659                                         Some Women      £13.73

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
655          Two
656          Two
657        Three
658         Five
659         Five

[660 rows x 3 columns]
(680, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
675  Harry Potter and the Chamber of Secrets (Harry...      £14.74
676                                 Gone with the Wind      £32.49
677  God Is Not Great: How Religion Poisons Everything      £27.80
678                          Girl With a Pearl Earring      £26.77
679           Fruits Basket, Vol. 4 (Fruits Basket #4)      £50.44

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
675          One
676        Three
677          One
678          One
679         Four

[680 rows x 3 columns]
(700, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
695  Wild: From Lost to Found on the Pacific Crest ...      £46.02
696                         Where'd You Go, Bernadette      £18.13
697                    When You Are Engulfed in Flames      £30.89
698  We the People: The Modern-Day Figures Who Have...      £31.95
699             We Are All Completely Beside Ourselves      £24.04

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
695        Three
696          One
697         Five
698        Three
699          One

[700 rows x 3 columns]

(720, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
715                                      The Travelers      £15.77
716  The Tipping Point: How Little Things Can Make ...      £10.02
717                          The Thing About Jellyfish      £48.77
718                                          The Stand      £57.86
719                       The Smitten Kitchen Cookbook      £23.59

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
715          One
716          Two
717          One
718          Two
719          One

[720 rows x 3 columns]
(740, 3)
                                Books Name Books Price Books Rating
0                     A Light in the Attic      £51.77        Three
1                       Tipping the Velvet      £53.74          One
2                               Soumission      £50.10          One
3                            Sharp Objects      £47.82         Four
4    Sapiens: A Brief History of Humankind      £54.23         Five
..                                     ...         ...          ...
735           The Nanny Diaries (Nanny #1)      £52.53         Five
736               The Name of God is Mercy      £37.25          Two
737   The Maze Runner (The Maze Runner #1)      £20.93          One
738                 The Lover's Dictionary      £58.09          Two
739                        The Lonely Ones      £43.59         Five

[740 rows x 3 columns]
(760, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
755  The Elegant Universe: Superstrings, Hidden Dim...      £13.03
756  The Disappearing Spoon: And Other True Tales o...      £57.35
757   The Devil Wears Prada (The Devil Wears Prada #1)      £44.29
758  The Demon-Haunted World: Science as a Candle i...      £52.25
759            The Day the Crayons Came Home (Crayons)      £26.33

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
755         Four
756         Five
757          One
758         Four
759         Five

[760 rows x 3 columns]
(780, 3)
                                 Books Name Books Price Books Rating
0                      A Light in the Attic      £51.77        Three
1                        Tipping the Velvet      £53.74          One
2                                Soumission      £50.10          One
3                             Sharp Objects      £47.82         Four
4     Sapiens: A Brief History of Humankind      £54.23         Five
..                                      ...         ...          ...
775     Spilled Milk: Based on a True Story      £49.51          One
776  Something Borrowed (Darcy & Rachel #1)      £48.96         Five
777      Something Blue (Darcy & Rachel #2)      £54.62          One
778                      Soldier (Talon #3)      £24.72          Two
779       Shopaholic & Baby (Shopaholic #5)      £46.45          Two

[780 rows x 3 columns]
(800, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
795  Packing for Mars: The Curious Science of Life ...      £56.68
796                     Outliers: The Story of Success      £14.16
797                                      Original Fake      £31.45
798                            Orange Is the New Black      £24.61
799              One for the Money (Stephanie Plum #1)      £32.87

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
795          Two
796          One
797        Three
798          Two
799          Two

[800 rows x 3 columns]
(820, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
815  Let's Pretend This Never Happened: A Mostly Tr...      £45.11
816                                 Legend (Legend #1)      £43.69
817         Lean In: Women, Work, and the Will to Lead      £25.02
818  Lamb: The Gospel According to Biff, Christ's C...      £55.50
819                    Lady Renegades (Rebel Belle #3)      £53.04

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
815          One
816         Four
817          One
818         Five
819         Five

[820 rows x 3 columns]
(840, 3)
                                   Books Name Books Price Books Rating
0                        A Light in the Attic      £51.77        Three
1                          Tipping the Velvet      £53.74          One
2                                  Soumission      £50.10          One
3                               Sharp Objects      £47.82         Four
4       Sapiens: A Brief History of Humankind      £54.23         Five
..                                        ...         ...          ...
835  Green Eggs and Ham (Beginner Books B-16)      £10.79         Four
836      Grayson, Vol 3: Nemesis (Grayson #3)      £42.72          One
837                                 Gratitude      £26.66         Five
838                                 Gone Girl      £37.60         Five
839                Golden (Heart of Dread #3)      £42.21         Four

[840 rows x 3 columns]
(860, 3)
                                   Books Name Books Price Books Rating
0                        A Light in the Attic      £51.77        Three
1                          Tipping the Velvet      £53.74          One
2                                  Soumission      £50.10          One
3                               Sharp Objects      £47.82         Four
4       Sapiens: A Brief History of Humankind      £54.23         Five
..                                        ...         ...          ...
855                      Darkfever (Fever #1)      £56.02          One
856                               Dark Places      £23.90         Five
857  Crazy Rich Asians (Crazy Rich Asians #1)      £49.13         Five
858                            Counting Thyme      £10.62          One
859                                    Cosmos      £36.17          Two

[860 rows x 3 columns]
(880, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
875         Beautiful Creatures (Caster Chronicles #1)      £21.55
876                                            Awkward      £38.02
877                                                Ash      £22.06
878                                  Are We There Yet?      £10.66
879  Are We Smart Enough to Know How Smart Animals ...      £56.58

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
875         Five
876          Two
877         Four
878        Three
879          One

[880 rows x 3 columns]

(900, 3)
                                Books Name Books Price Books Rating
0                     A Light in the Attic      £51.77        Three
1                       Tipping the Velvet      £53.74          One
2                               Soumission      £50.10          One
3                            Sharp Objects      £47.82         Four
4    Sapiens: A Brief History of Humankind      £54.23         Five
..                                     ...         ...          ...
895                 New Moon (Twilight #2)      £12.86         Four
896                                   Life      £31.58         Five
897         Kindle Paperwhite User's Guide      £34.00        Three
898                          H is for Hawk      £57.42         Five
899   Girl Online On Tour (Girl Online #2)      £53.47          One

[900 rows x 3 columns]
(920, 3)
                                         Books Name Books Price Books Rating
0                              A Light in the Attic      £51.77        Three
1                                Tipping the Velvet      £53.74          One
2                                        Soumission      £50.10          One
3                                     Sharp Objects      £47.82         Four
4             Sapiens: A Brief History of Humankind      £54.23         Five
..                                              ...         ...          ...
915                                       The Tumor      £41.56         Five
916                       The Story of Hong Gildong      £43.19         Four
917                                 The Silent Wife      £12.34         Five
918  The Silent Twin (Detective Jennifer Knight #3)      £36.25        Three
919                                The Selfish Gene      £29.45          One

[920 rows x 3 columns]
(940, 3)
                                         Books Name Books Price Books Rating
0                              A Light in the Attic      £51.77        Three
1                                Tipping the Velvet      £53.74          One
2                                        Soumission      £50.10          One
3                                     Sharp Objects      £47.82         Four
4             Sapiens: A Brief History of Humankind      £54.23         Five
..                                              ...         ...          ...
935       The Girl In The Ice (DCI Erika Foster #1)      £15.85        Three
936  The End of the Jesus Era (An Investigation #1)      £14.40          One
937           The Edge of Reason (Bridget Jones #2)      £19.18         Four
938                   The Complete Maus (Maus #1-2)      £10.64        Three
939                         The Communist Manifesto      £14.76        Three

[940 rows x 3 columns]
(960, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
955                        Paradise Lost (Paradise #1)      £24.96
956             Paper Girls, Vol. 1 (Paper Girls #1-5)      £21.71
957  Ouran High School Host Club, Vol. 1 (Ouran Hig...      £29.87
958                               Origins (Alphas 0.5)      £28.99
959                              One Second (Seven #7)      £52.94

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
955          One
956         Four
957        Three
958          One
959          Two

[960 rows x 3 columns]
(980, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
975                             Icing (Aces Hockey #2)      £40.44
976  Hawkeye, Vol. 1: My Life as a Weapon (Hawkeye #1)      £45.24
977  Having the Barbarian's Baby (Ice Planet Barbar...      £34.96
978               Giant Days, Vol. 1 (Giant Days #1-4)      £56.76
979           Fruits Basket, Vol. 1 (Fruits Basket #1)      £40.28

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
975         Four
976        Three
977         Four
978         Four
979         Five

[980 rows x 3 columns]
(1000, 3)
                                            Books Name Books Price  \
0                                 A Light in the Attic      £51.77
1                                   Tipping the Velvet      £53.74
2                                           Soumission      £50.10
3                                        Sharp Objects      £47.82
4                Sapiens: A Brief History of Humankind      £54.23
..                                                 ...         ...
995  Alice in Wonderland (Alice's Adventures in Won...      £55.53
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)      £57.06
997  A Spy's Devotion (The Regency Spies of London #1)      £16.97
998                1st to Die (Women's Murder Club #1)      £53.98
999                 1,000 Places to See Before You Die      £26.08

    Books Rating
0          Three
1            One
2            One
3           Four
4           Five
..           ...
995          One
996         Four
997         Five
998          One
999         Five

[1000 rows x 3 columns]